name: Create Release

on:
  push:
    branches:
      - 'release'
    paths:
      - 'package.json'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
            fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
          cache: npm

      - name: get package version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master

      - name: check tag exists
        uses: mukunku/tag-exists-action@v1.0.0
        id: check-tag
        with:
          tag: v${{ steps.package-version.outputs.current-version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: npm ci
        if: steps.check-tag.outputs.exists == 'false'
        run: npm ci

      - name: create artifact
        if: steps.check-tag.outputs.exists == 'false'
        run: npm run build
      
      - name: archive artifact
        if: steps.check-tag.outputs.exists == 'false'
        run: zip -rj better-japanese.zip ./build

      - name: create release
        if: steps.check-tag.outputs.exists == 'false'
        uses: softprops/action-gh-release@v1
        with: 
          name: v${{ steps.package-version.outputs.current-version }}
          tag_name: v${{ steps.package-version.outputs.current-version }}
          files: better-japanese.zip
